import type { Metadata } from "next";
import { Kumbh_Sans } from 'next/font/google'

import "./globals.css";
import { cn } from '@/lib/utils'

const kumbh = Kumbh_Sans({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang='en'>
      <body className={cn(kumbh.className, 'antialiased min-h-screen')}>{children}</body>
    </html>
  )
}
